import Container from "typedi";

export enum Envs {
  EXAMPLE_ACCESS_TOKEN = "EXAMPLE_ACCESS_TOKEN",
  EXAMPLE_BASE_URL = "EXAMPLE_BASE_URL",
  LOGIN_ACCESS_TOKEN = "LOGIN_ACCESS_TOKEN",
  TCR_BASE_URL = "TCR_BASE_URL",
  TCR_ACCESS_TOKEM = "TCR_ACCESS_TOKEM",
  PRODUCT_SEARCH_ACCESS_TOKEN = "PRODUCT_SEARCH_ACCESS_TOKEN",
  PRODUCT_SEARCH_BASE_URL = "PRODUCT_SEARCH_BASE_URL",
}

export function configEnvs() {
  Container.set(Envs.EXAMPLE_ACCESS_TOKEN, process.env.EXAMPLE_ACCESS_TOKEN);
  Container.set(Envs.EXAMPLE_BASE_URL, process.env.EXAMPLE_BASE_URL);
  Container.set(Envs.LOGIN_ACCESS_TOKEN,process.env.LOGIN_ACCESS_TOKEN);
  Container.set(Envs.TCR_BASE_URL,process.env.TCR_BASE_URL);
  Container.set(Envs.TCR_ACCESS_TOKEM , process.env.TCR_ACCESS_TOKEM);
  Container.set(Envs.PRODUCT_SEARCH_ACCESS_TOKEN, process.env.PRODUCT_SEARCH_ACCESS_TOKEN);
  Container.set(Envs.PRODUCT_SEARCH_BASE_URL, process.env.PRODUCT_SEARCH_BASE_URL);
}
